version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    #command: gunicorn momo_ristorante.wsgi -b 0.0.0.0:8000
    environment:
      - SECRET_KEY=django-insecure-v34h48=*da_@x!pa)8w1u2x38o$a&yxi!9f(2@s@68+t%ds!t_<
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    
    depends_on:
      - db
  
  db:
    image: postgres:11