# Generated by Django 3.2 on 2021-04-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('homepage_id', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('subtitle', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('link_url', models.TextField(blank=True)),
                ('image_url', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteurl', models.TextField()),
                ('blogname', models.TextField()),
                ('blogdescription', models.TextField(blank=True)),
                ('users_can_register', models.TextField()),
                ('admin_email', models.TextField()),
                ('mailserver_url', models.TextField()),
                ('mailserver_login', models.TextField()),
            ],
        ),
    ]
