# Generated by Django 3.2 on 2021-05-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='homepage_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
