# Generated by Django 3.2 on 2021-05-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_homepage_homepage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='blogdescription',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='blogname',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='siteurl',
        ),
        migrations.AddField(
            model_name='setting',
            name='site_description',
            field=models.CharField(default='Lorem ipsum ', max_length=200),
        ),
        migrations.AddField(
            model_name='setting',
            name='site_name',
            field=models.CharField(default='MOMO Ristorante', max_length=100),
        ),
        migrations.AddField(
            model_name='setting',
            name='site_url',
            field=models.TextField(default='http://127.0.0.1:8000/', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=models.TextField(blank=True, default='subtitle XYZ'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='link_url',
            field=models.CharField(blank=True, default='link_url', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle',
            field=models.CharField(default='subtitle XYZ', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(default='Section XYZ', max_length=100),
        ),
        migrations.AlterField(
            model_name='setting',
            name='admin_email',
            field=models.CharField(default='admin@email.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='setting',
            name='mailserver_login',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='setting',
            name='mailserver_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='setting',
            name='users_can_register',
            field=models.BooleanField(default=0),
        ),
    ]
