# Generated by Django 3.2 on 2021-05-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210523_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='create_date',
        ),
    ]
