# Generated by Django 3.2 on 2021-05-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_blog_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='create_by',
            new_name='author',
        ),
    ]
