# Generated by Django 3.2 on 2021-06-16 09:22

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_blog_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=150, validators=[core.validators.validate_blog]),
        ),
    ]
