# Generated by Django 3.2 on 2021-06-16 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='create_by',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='create_date',
        ),
        migrations.AddField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
