# Generated by Django 3.2 on 2021-06-17 10:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField()),
                ('person', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('status', models.BooleanField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
