# Generated by Django 3.2 on 2021-04-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
    ]
